feature/add-pix-payment-method-pagarme-V3
pagarme/pagarme-php pull request #379
Opened 2020-11-17 03:51 UTC by Matheus-Maciel

### Descrição
O PR visa adicionar o método de pagamento PIX no SDK de PHP V3. Essa versão não possui testes automatizados.
<!Insira aqui o contexto/motivo deste Pull Request.>

### Número da Issue

Não existe
<!Insira aqui o número da Issue referente à este Pull Request.>

### Testes Realizados
Por hora foram realizados apenas testes manuais visto que os testes do SDK precisam ser refatorados
<!Descreva aqui todos os detalhes realizados para assegurar o Pull Request. Coloque todos os dados possíveis: versões dos recursos, módulos extras adicionados ao teste :)>

<!NÃO SE ESQUEÇA DE: Marcar um dos desenvolvedores do Pagar.me para review.>

2020-11-17 20:26 UTC, willian-soaresferreira requested changes
Nesse PR aqui os testes passaram: https://github.com/pagarme/pagarme-php/pull/371
Então acredito que é só corrigir o erro que está dando :)

2020-11-26 17:53 UTC, willian-soaresferreira approved these changes
Boa, aprovado! Acho que só é bacana juntar os commits que mexeram em alguns arquivos e depois voltaram ao que era antes, pra evitar alguma confusão futura. E também alterar a descrição do PR, a parte que diz que a versão não tem testes automatizados, pois agora eles já estão passando com sucesso :)

Obs.: Entendo que tudo bem ainda não ter testes específicos de PIX, pois no momento precisa de companies e configurações específicas pra poder testar.

2020-12-11 11:45 UTC, rstriquer commented
Olá amigos. Espero que eu não esteja escrevendo e fazendo perguntas nos locais errados, mas preciso perguntar. Existe alguma previsão de quando essa PR estará no master? Existe outra PR de PIX? Essa PR entrará na versão 3 ainda ou só entrará na 4, saberiam dizer? Obrigado.

2020-12-11 16:27 UTC, willian-soaresferreira commented
Oi @rstriquer, tudo bem? A previsão de deploy da v3 do nosso SDK é 15/12 terça-feira. Para a v4 não precisou de alteração no SDK, devido a forma que ele foi construído para aceitar os parâmetros através de um array, então basta enviar os novos campos referentes ao PIX. Exemplo:
```
  'payment_method' => 'pix',
  'pix_expiration_date' => '2020-01-11',
  'pix_additional_fields' => [
    [
        'name' => 'Quantidade',
        'value'=>  '2'
    ]
  ],
```

Atualmente para ativar o PIX aqui na Pagar.me, mesmo que em ambiente de testes, você pode enviar um e-mail para suporte@pagar.me, ok?

2020-12-11 16:33 UTC, rstriquer commented
@willian-soaresferreira a versão marcada no home do projeto é a v3.8.2, entendo que ela é a stable, mas eu posso utilizar, p. ex., a v4.1.2 em produção, ela está marcada como stable também? Grato.

2020-12-11 16:40 UTC, willian-soaresferreira commented
Oi @rstriquer! A versão mais atual e que sugerimos o uso para novos projetos é a v4, e o build mais recente é de fato o v.4.1.2. Inclusive a branch "main" do projeto pagarme-php é a v4. Ainda damos manutenção na v3 no momento pois tem clientes com projetos já existentes que ainda a utilizam. Qualquer dúvida por favor me avise :)

2020-12-14 14:40 UTC, merged

2021-04-01 16:13 UTC, bruno-barros commented
Olá pessoal,
existe alguma documentação sobre a transação com PIX?
Me parece que o envio da requisição é só alterar/adicionar os campos do PIX, mas como tratar o retorno e gerar o QR Code?

2021-04-09 16:42 UTC, Matheus-Maciel commented
O retorno da API é o parâmetro "pix_qr_code" que pode ser utilizado no aplicativo de banco do comprador ou renderizado na forma de QR Code visual. Essa etapa de renderizar já é por conta da aplicação da loja.
Para testar a ferramenta eu recomendo o seguinte site: 
https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=
Supondo que o retorno da API foi o seguinte:
00020101021226900014br.gov.bcb.pix2568pix-sandbox.stone.com.br/pix/v2/c2ac02b6-33fa-48c4-a50b-3614334214715204000053039865406300.005802BR5905Macil6014RIO DE JANEIRO62290525a0284d3a34c94da690e7100e66304ED6A
Basta adicionar o retorno da API da Pagar.me para gerar o QR Code escaneável:
https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=00020101021226900014br.gov.bcb.pix2568pix-sandbox.stone.com.br/pix/v2/c2ac02b6-33fa-48c4-a50b-3614334214715204000053039865406300.005802BR5905Macil6014RIO%20DE%20JANEIRO62290525a0284d3a34c94da690e7100e66304ED6A
![qrcode](https://user-images.githubusercontent.com/44435105/114213429-5862fd00-9939-11eb-82e4-afe3ee9cafaa.png)

2021-04-19 17:58 UTC, bruno-barros commented
Obrigado @Matheus-Maciel 
Deve existir libs em PHP para gerar a imagem, não? 
Como nunca mexi com QR code, não sei se esse retorno é padronizado.